### ISSUE TITLE
isActive marker for / url

### ISSUE THREAD

**Issue by damsfx** [wintercms/wn-pages-plugin#27]
- Winter CMS Build: 1.2.1
- Pages Plugin Version: 2.0.2
- PHP Version: 8.0

### Description:
A page with `/` url is not marked as active (`isActive = false`) when visiting website home page.

### Steps To Reproduce:
Add some statics pages, one having `/` has URL.   

`..\meta\static-pages.yaml` file :
```yaml
static-pages:
    index: {  }
    page2: {  }
    page3: {  }
```
` ...\content\static-pages\index.htm` file :
```twig
[viewBag]
title = "Home
url = "/"
layout = "default"
is_hidden = 0
navigation_hidden = 0
==
Lorem ipsum dolor sit amet consectetur adipisicing elit. Laboriosam, impedit.
```

Setting a menu : 
```yaml
name: 'Top - Navbar'
items:
    -
        title: main
        nesting: null
        type: all-static-pages
        url: null
        code: ''
        reference: null
        cmsPage: null
        replace: 1
        viewBag:
            isHidden: '0'
            cssClass: ''
            isExternal: '0'
``` 

Visiting `http://acme.tld` doesn't mark the menu item as active, while visiting `http://acme.tld/` does.   
I am missing something ?
